version: '3.8'

services:
    consumer:
        container_name: nestjs_consumer_prod
        image: nestjs-consumer-prod:1.0.0
        depends_on:
        - kafka
        build:
            context: ./consumer
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
        networks:
            - kafka-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped    
        
    producer:
        container_name: nestjs_producer_prod
        image: nestjs-producer-prod:1.0.0
        depends_on:
        - kafka
        build:
            context: ./producer
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3002:3000
        networks:
            - kafka-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped 
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        networks:
            - kafka-network
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
        - zookeeper
        ports:
        - 9092:9092
        networks:
            - kafka-network
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_LISTENERS: INTERNAL://:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT

    control-center:
        image: confluentinc/cp-enterprise-control-center:6.0.1
        hostname: control-center
        depends_on:
        - kafka
        ports:
        - "9021:9021"
        networks:
            - kafka-network
        environment:
            CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
            CONTROL_CENTER_REPLICATION_FACTOR: 1
            PORT: 9021   
        
networks:
    kafka-network:
